//
//  StateMachineCommon.h
//  cnepay_developkit_bt
//
//  Created by cqh on 15/5/24.
//  Copyright (c) 2015年 Cnepay. All rights reserved.
//

#import <Foundation/Foundation.h>

typedef NS_ENUM(NSUInteger, EVENT) {
    //扫描
    EVENT_SCAN = 100,
    EVENT_SCAN_STOPPED,
    EVENT_SCAN_FAILURE,
    EVENT_FOUND_DEVICE,

    //中断扫描
    EVENT_DISSCAN,
    EVENT_DISSCAN_SUCCESS,
    EVENT_DISSCAN_FAILURE,
    //连接
    EVENT_CONNECT,
    EVENT_CONNECT_SUCCESS,
    EVENT_CONNECT_FAILURE,
    //断开
    EVENT_DISCONNECT,
    EVENT_DISCONNECT_SUCCESS,
    EVENT_DISCONNECT_FAILURE,
    //交易
    EVENT_DEAL,
    EVENT_DEAL_SUCCESS,
    EVENT_DEAL_FAILURE,
    //中断
    EVENT_INTERUPT,
    //获取设备信息
    EVENT_FETCHDEVICEINFO,
    EVENT_FETCHDEVICEINFO_SUCCESS,
    EVENT_FETCHDEVICEINFO_FAILURE,
    EVENT_FETCHDEVICEINFO_KSN_UNPAIRED,
    
    //设置工作秘钥
    EVENT_SETWORKKEY,
    EVENT_SETWORKKEY_SUCCESS,
    EVENT_SETWORKKEY_FAILURE,
    //写入aid，rid
    EVENT_WRITEAIDRID,
    EVENT_WRITEAIDRID_SUCCESS,
    EVENT_WRITEAIDRID_FAILURE,
    //休眠
    EVENT_STANDBY,
    //等待刷卡
    EVENT_WAITCARD,
    EVENT_WAITCARD_SUCCESS,
    EVENT_WAITCARD_FAILURE,
    //读取卡信息
    EVENT_READCARD,
    EVENT_READCARD_SUCCESS,
    EVENT_READCARD_FAILURE,
    EVENT_READCARD_FINISH,
    //读取pin
    EVENT_READPIN,
    EVENT_READPIN_SUCCESS,
    EVENT_READPIN_FAILURE,
    //读取MAC
    EVENT_READMAC,
    EVENT_READMAC_SUCCESS,
    EVENT_READMAC_FAILURE,
    //联机
    EVENT_ONLINE,
    EVENT_ONLINE_SUCCESS,
    EVENT_ONLINE_FAILURE,
    //显示
    EVENT_DISPAY,
    EVENT_DISPAY_SUCCESS,
    EVENT_DISPAY_FAILURE,
    //异常状态
    EVENT_EXCEPTION_LOSE,
    //差数为空
    EVENT_AIDRID_NULL,
    EVENT_WORKKEY_NULL,
    //再次连接
    EVENT_REPEAT_CONNECT,
    //PBOC
    EVENT_STOPPBOC,
    EVENT_STOPPBOC_SUCCESS,
    EVENT_STOPPBOC_FAILURE,
};

typedef NS_ENUM(NSUInteger, ACTION) {
    ACTION_CHOOSEDEVICE = 0,
    ACTION_SCAN,
    ACTION_DISSCAN,
    ACTION_CONNECT,
    ACTION_DISCONNECT,
    ACTION_DEAL,
    ACTION_INTERRUPT,
    ACTION_MAC,
    ACTION_ONLINE,
    ACTION_DISPLAY,
    ACTION_CLEAR,
    ACTION_STOPPBOC,
    ACTION_RESIGNIN,
};

FOUNDATION_EXPORT NSString* const EventMapping [];
